name: dev-builds
on: [push]

jobs:
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 10, 12]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - if: matrix.node-version <= 8
      run: |
        npm run setup
        npm run build
        npm run test:node8
      env:
        OTPLIB_SETUP_EXTRAS: skip
        OTPLIB_BUILD_BUNDLE: false
        OTPLIB_BUILD_INCLUDE_BUFFER: false
        OTPLIB_BUILD_COPY_META: false
    - if: matrix.node-version > 8
      run: |
        npm run setup
        npm run build
        npm run test:module
      env:
        OTPLIB_SETUP_EXTRAS: testmodule
        OTPLIB_BUILD_BUNDLE: false
        OTPLIB_BUILD_INCLUDE_BUFFER: false
        OTPLIB_BUILD_COPY_META: false

  test-browser:
    runs-on: ubuntu-latest
    needs: [test-node]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - run: |
        npm run setup
        npm run build
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        OTPLIB_SETUP_EXTRAS: testbrowser
        OTPLIB_BUILD_MODULE: false
        OTPLIB_BUILD_COPY_META: false
    - uses: docker://buildkite/puppeteer:v1.15.0
      with:
        args: npm run test:browser

  master-builds:
    runs-on: ubuntu-latest
    needs: [test-node, test-browser]
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v1
      if: github.ref == 'refs/heads/master'
      with:
        node-version: 10
    - name: setup and build artifact
      if: github.ref == 'refs/heads/master'
      run: |
        npm run setup
        ./scripts/build-artifact.sh
      env:
        OTPLIB_SETUP_EXTRAS: skip
    - uses: actions/upload-artifact@master
      if: github.ref == 'refs/heads/master'
      with:
        name: otplib-ci-master
        path: builds/otplib
